/* eslint-disable camelcase */

import { ReactNode } from "react";

import { Noto_Sans } from "next/font/google";

import style from "./layout.module.scss";

import type { Metadata } from "next";

import "./reset.css";
import "./globals.scss";

const notoSans = Noto_Sans({
	weight: ["300", "400", "500", "600", "700", "900"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-noto-sans",
});

export const metadata: Metadata = {
	title: "BeSigned",
	description: "Generated by BeSigned",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${notoSans.className} ${style.layoutBackground}`}>{children}</body>
		</html>
	);
}
