/* eslint-disable camelcase */
import { ReactNode } from "react";

import { Noto_Sans } from "next/font/google";

import type { Metadata } from "next";

import "./reset.css";
import "./globals.scss";

const notoSans = Noto_Sans({
	weight: ["300", "600", "900"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "BeSigned",
	description: "Generated by BeSigned",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${notoSans.className}`}>{children}</body>
		</html>
	);
}
